matrix:
  include:
    - language: python
      python:
        - '3.7'
      script:
        - python test.py
    - language: node_js
      node_js:
        - 'node'
      requirements_file: ''
      install:
        - npm install
      sudo: false
notifications:
  email:
    - evantayloryates@gmail.com